volumes:
  pg_data:

services:
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: postgresql.Dockerfile
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 10s
      timeout: 45s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - LANG=pt_BR.UTF-8
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./create_backend.sql:/docker-entrypoint-initdb.d/create_backend.sql
    networks:
      - backend

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    networks:
      - backend

networks:
  backend:
    driver: bridge

